export const Recipe = (
        id,
        name, 
        ingredients2,
        amounts, 
        steps2, 
        tags, 
        allergens,
        caloriesPerServing,
        cost,
        difficulty,
        prepTime,
        totalTime,
        url,
        vegan,
        video,
        image,
        nutrition,
    ) => { 
    return {
        id: id,
        name: name, 
        ingredients2: ingredients2, 
        amounts: amounts, 
        steps2: steps2, 
        tags: tags,
        allergens: allergens,
        caloriesPerServing: caloriesPerServing,
        cost: cost,
        difficulty: difficulty,
        prepTime: prepTime,
        totalTime: totalTime,
        url: url,
        vegan: vegan,
        video: video,
        image: image,
        nutrition: nutrition
    } 
}